name: Tests

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  linter:
    name: Linter and Formatter
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v6
      with:
        fetch-depth: 0

    - uses: actions/setup-python@v6
      name: Install Python
      with:
        python-version: "3.14"
    - run: pip install uv --upgrade

    - name: Install dependencies
      run: |
        uv venv
        uv pip install hatch
        uv pip install .
        uv pip install pybind11-stubgen

    - name: Lint with Ruff
      run: uv run hatch run lint:lint

    - name: Format check with black
      run: uv run hatch run lint:format

    - name: Check stubs
      run: |
        uv run pybind11-stubgen hvdaccelerators.vpdq -o src/
        if ! git diff --exit-code src/hvdaccelerators/vpdq.pyi; then
          echo "Stubs are out of date. Regenerate with "hatch run stubs:gen" and commit the result."
          exit 1
        fi
        uv run hatch run stubs:check

  unittest:
    name: Unit Test
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14", "3.x"]
        os: [ubuntu-24.04, ubuntu-24.04-arm, macos-14, macos-15, macos-26, windows-2025]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v6
      with:
        fetch-depth: 0

    - uses: actions/setup-python@v6
      name: Install Python
      with:
        python-version: ${{ matrix.python-version }}
    - run: pip install uv --upgrade

    - name: Install dependencies
      run: |
        uv venv
        uv pip install hatch

    - name: Unit test
      run: uv run hatch run test:all
