name: Build Python wheels

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Install Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.14"
      - run: |
          pip install uv --upgrade
          uv venv
          uv pip install hatch
      - name: Build sdist
        run: uv run hatch build --clean --target sdist dist
      - uses: actions/upload-artifact@v7
        with:
          name: dist-sdist
          path: dist/*.tar.gz

  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest] # This doesn't affect the resulting package version, so floating to latest is ok
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v6
        name: Install Python
        with:
          python-version: "3.14"
      - run: pip install uv --upgrade

      - name: Build wheels on ${{ matrix.os }} using cibuildwheel
        uses: pypa/cibuildwheel@v3.4.0
        env:
          CIBW_BUILD: "cp310-* cp311-* cp312-* cp313-* cp314-*"
          CIBW_SKIP: "*-musllinux_*"
          CIBW_ARCHS: auto64

      - name: Upload ${{ matrix.os }} wheels
        uses: actions/upload-artifact@v7
        with:
          name: dist-${{ matrix.os }}
          path: wheelhouse/*.whl
          if-no-files-found: error
